allow-lan: true
external-controller: 127.0.0.1:9090
log-level: info
mixed-port: 7890
mode: rule
proxies:
- name: proxy-1
  port: 80
  server: 103.125.31.222
  type: http
  udp: true
- name: proxy-2
  port: 3128
  server: 43.205.124.6
  type: http
  udp: true
- name: proxy-3
  port: 5566
  server: 158.101.175.124
  type: http
  udp: true
- name: proxy-4
  port: 80
  server: 23.247.136.254
  type: http
  udp: true
- name: proxy-5
  port: 80
  server: 34.44.49.215
  type: http
  udp: true
- name: proxy-6
  port: 80
  server: 34.81.160.132
  type: http
  udp: true
- name: proxy-7
  port: 80
  server: 174.138.119.88
  type: http
  udp: true
- name: proxy-8
  port: 80
  server: 159.65.245.255
  type: http
  udp: true
- name: proxy-9
  port: 80
  server: 31.220.78.244
  type: http
  udp: true
- name: proxy-10
  port: 8443
  server: 45.125.67.37
  type: http
  udp: true
- name: proxy-11
  port: 80
  server: 133.18.234.13
  type: http
  udp: true
- name: proxy-12
  port: 1081
  server: 86.104.74.110
  type: http
  udp: true
- name: proxy-13
  port: 80
  server: 12.50.107.221
  type: http
  udp: true
- name: proxy-14
  port: 80
  server: 168.138.50.91
  type: http
  udp: true
- name: proxy-15
  port: 80
  server: 109.236.88.82
  type: http
  udp: true
- name: proxy-16
  port: 3128
  server: 80.74.54.148
  type: http
  udp: true
- name: proxy-17
  port: 3128
  server: 46.47.197.210
  type: http
  udp: true
- name: proxy-18
  port: 8090
  server: 183.110.216.159
  type: http
  udp: true
- name: proxy-19
  port: 80
  server: 103.253.43.144
  type: http
  udp: true
- name: proxy-20
  port: 80
  server: 194.150.110.134
  type: http
  udp: true
- name: proxy-21
  port: 80
  server: 12.50.107.217
  type: http
  udp: true
- name: proxy-22
  port: 80
  server: 91.132.92.231
  type: http
  udp: true
- name: proxy-23
  port: 80
  server: 12.50.107.219
  type: http
  udp: true
- name: proxy-24
  port: 80
  server: 172.237.73.24
  type: http
  udp: true
- name: proxy-25
  port: 80
  server: 219.93.101.63
  type: http
  udp: true
- name: proxy-26
  port: 443
  server: 212.224.88.212
  type: http
  udp: true
- name: proxy-27
  port: 80
  server: 221.124.203.24
  type: http
  udp: true
- name: proxy-28
  port: 80
  server: 103.151.20.131
  type: http
  udp: true
- name: proxy-29
  port: 80
  server: 139.162.200.213
  type: http
  udp: true
- name: proxy-30
  port: 80
  server: 95.216.49.153
  type: http
  udp: true
- name: proxy-31
  port: 80
  server: 97.74.87.226
  type: http
  udp: true
- name: proxy-32
  port: 80
  server: 212.231.191.23
  type: http
  udp: true
- name: proxy-33
  port: 80
  server: 12.50.107.222
  type: http
  udp: true
- name: proxy-34
  port: 80
  server: 38.60.196.214
  type: http
  udp: true
- name: proxy-35
  port: 80
  server: 27.34.242.98
  type: http
  udp: true
- name: proxy-36
  port: 80
  server: 143.42.66.91
  type: http
  udp: true
- name: proxy-37
  port: 80
  server: 196.1.97.198
  type: http
  udp: true
- name: proxy-38
  port: 80
  server: 154.65.39.7
  type: http
  udp: true
- name: proxy-39
  port: 80
  server: 12.50.107.220
  type: http
  udp: true
- name: proxy-40
  port: 80
  server: 185.82.218.85
  type: http
  udp: true
- name: proxy-41
  port: 3128
  server: 103.94.52.70
  type: http
  udp: true
- name: proxy-42
  port: 30226
  server: 113.11.126.238
  type: http
  udp: true
- name: proxy-43
  port: 80
  server: 176.61.151.123
  type: http
  udp: true
- name: proxy-44
  port: 80
  server: 89.58.55.33
  type: http
  udp: true
- name: proxy-45
  port: 80
  server: 219.65.73.81
  type: http
  udp: true
- name: proxy-46
  port: 80
  server: 190.119.132.61
  type: http
  udp: true
- name: proxy-47
  port: 9090
  server: 180.191.234.200
  type: http
  udp: true
proxy-groups:
- interval: 300
  name: auto
  proxies:
  - proxy-1
  - proxy-2
  - proxy-3
  - proxy-4
  - proxy-5
  - proxy-6
  - proxy-7
  - proxy-8
  - proxy-9
  - proxy-10
  - proxy-11
  - proxy-12
  - proxy-13
  - proxy-14
  - proxy-15
  - proxy-16
  - proxy-17
  - proxy-18
  - proxy-19
  - proxy-20
  - proxy-21
  - proxy-22
  - proxy-23
  - proxy-24
  - proxy-25
  - proxy-26
  - proxy-27
  - proxy-28
  - proxy-29
  - proxy-30
  - proxy-31
  - proxy-32
  - proxy-33
  - proxy-34
  - proxy-35
  - proxy-36
  - proxy-37
  - proxy-38
  - proxy-39
  - proxy-40
  - proxy-41
  - proxy-42
  - proxy-43
  - proxy-44
  - proxy-45
  - proxy-46
  - proxy-47
  tolerance: 100
  type: url-test
  url: http://www.gstatic.com/generate_204
- name: select
  proxies:
  - proxy-1
  - proxy-2
  - proxy-3
  - proxy-4
  - proxy-5
  - proxy-6
  - proxy-7
  - proxy-8
  - proxy-9
  - proxy-10
  - proxy-11
  - proxy-12
  - proxy-13
  - proxy-14
  - proxy-15
  - proxy-16
  - proxy-17
  - proxy-18
  - proxy-19
  - proxy-20
  - proxy-21
  - proxy-22
  - proxy-23
  - proxy-24
  - proxy-25
  - proxy-26
  - proxy-27
  - proxy-28
  - proxy-29
  - proxy-30
  - proxy-31
  - proxy-32
  - proxy-33
  - proxy-34
  - proxy-35
  - proxy-36
  - proxy-37
  - proxy-38
  - proxy-39
  - proxy-40
  - proxy-41
  - proxy-42
  - proxy-43
  - proxy-44
  - proxy-45
  - proxy-46
  - proxy-47
  type: select
rules:
- MATCH,auto
