proxies:
- name: proxy-1
  port: 80
  server: 103.125.31.222
  type: http
  udp: true
- name: proxy-2
  port: 80
  server: 143.42.66.91
  type: http
  udp: true
proxy-groups:
- interval: 300
  name: auto
  proxies:
  - proxy-1
  - proxy-2
  type: url-test
  url: http://www.gstatic.com/generate_204
